### ISSUE TITLE
Ollama模型失效了

### ISSUE THREAD

**Issue by Strivy-ZSY** [nicepkg/aide#108]
按照参考文档配置的Ollama，一个月前还可以正常使用，现在一直显示的“Aide正在处理中...”
以下是我的配置信息
    "aide.openaiBaseUrl": "http://localhost:11434/v1",
    "aide.openaiModel": "phi3.5:latest",
    "aide.openaiKey": "sk-ollama",
    "aide.aiCommand": "ollama run gemma2:9b",
    
    在使用的其他Ollama的软件中，都可以正常使用

**Comment by jhnmyr233** [comment]
同样遇到了这个问题，一直显示在处理中。
"aide.openaiBaseUrl": "http://localhost:11434/v1",
"aide.openaiModel": "ollama3.1",
"aide.openaiKey": "sk-ollama",
"aide.aiCommand": "ollama run ollama3.1",
![设置 - 无标题 (工作区) - Visual Studio Code 2024_11_7 19_48_44](https://github.com/user-attachments/assets/af3744cb-fe6d-42ea-8d02-1097a095ae0e)

**Comment by Strivy-ZSY** [comment]
目前该问题尚未解决，我更改使用和Ollama联动的Contiunce了
详细信息可以参考下面的博客
https://ollama.com/blog/continue-code-assistant
和aide的使用方式不同，但其在功能性上更灵活。您可以试试😊

**Comment by jhnmyr233** [comment]
很棒的解决方案， 感谢您的分享🎉

**Comment by Strivy-ZSY** [comment]
不客气，能帮到您很高兴🤗
