### ISSUE TITLE
下载的地址可以自己设置吗？

### ISSUE THREAD

**Issue by bnufw** [nicepkg/aide#122]

**Comment by 2214962083** [comment]
什么下载地址，不理解你的问题

**Comment by bnufw** [comment]
就是你缓存上传文件的地址，我看是默认存在c盘了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月6日(周五) 中午12:08
收件人: ***@***.***&gt;;
抄送: "Zhu ***@***.******@***.***&gt;;
主题: Re: [nicepkg/aide] 下载的地址可以自己设置吗？ (Issue #122)




 
什么下载地址，不理解你的问题

**Comment by 2214962083** [comment]
我还是不理解你的意思，我的软件里并没有上传功能也没有缓存什么上传文件。

**Comment by bnufw** [comment]
就是数据设置中的应用数据和应用日志，默认是在c盘
中，而且好像
是不能改的

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月6日(周五) 中午12:12
收件人: ***@***.***&gt;;
抄送: "Zhu ***@***.******@***.***&gt;;
主题: Re: [nicepkg/aide] 下载的地址可以自己设置吗？ (Issue #122)




 
我还是不理解你的意思，我的软件里并没有上传功能也没有缓存什么上传文件。

**Comment by 2214962083** [comment]
这是vscode的行为规则，和aide无关

**Comment by bnufw** [comment]
好的，我才发现我回复错了，但是总之，感谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月6日(周五) 中午12:16
收件人: ***@***.***&gt;;
抄送: "Zhu ***@***.******@***.***&gt;;
主题: Re: [nicepkg/aide] 下载的地址可以自己设置吗？ (Issue #122)




 
这是vscode的行为规则，和aide无关

**Comment by 2214962083** [comment]
不客气
