### ISSUE TITLE
插件突然无法正常工作,api已确认是可用的,我不知道是因为我改了设置还是怎么回事

### ISSUE THREAD

**Issue by zhongweijian-svg** [nicepkg/aide#123]
![image](https://github.com/user-attachments/assets/77953921-d60e-4987-89ed-05151a52941c)
就这样一直空转,
![image](https://github.com/user-attachments/assets/e471aee7-4b2f-435c-8813-ef9483d4fae4)
我的代理也没有问题

**Comment by zhongweijian-svg** [comment]
![image](https://github.com/user-attachments/assets/e2197103-2213-469b-b6ee-63398750c745)
貌似只能传过去一丁点信息,返回不了.

**Comment by 2214962083** [comment]
你是否装了fitten code、gpt-runner之类的插件。它们会覆写fetch，导致原生fetch stream出问题，禁用他们重启VS code再试试

**Comment by zhongweijian-svg** [comment]
是的。。
