### ISSUE TITLE
关于文档的优化建议

### ISSUE THREAD

**Issue by lc6464** [nicepkg/aide#14]
现有的文档直接依托 GitHub 在线预览进行，似乎显得不够优雅和便捷。
是否考虑通过类似于如下的方式优化它？
如：
- 使用 vitepress 或 readthedocs 等文档工具并基于 Actions 和 Pages 部署
- GitHub Wiki

由于我对这些文档工具了解不多，如有不合适的地方还请谅解。
另外，现在文件较少，尚比较容易组织，但如果以后文档会变长变多的话还是早做打算比较好。

**Comment by 2214962083** [comment]
非常好的建议，一旦文档更多，我会考虑建立一个文档网站

**Comment by 2214962083** [comment]
Aide 文档网站已上线：https://aide.nicepkg.cn/

**Comment by lc6464** [comment]
🎉🎉🎉
