### ISSUE TITLE
安装后显示未找到扩展

### ISSUE THREAD

**Issue by Shadow403** [nicepkg/aide#15]
System: `Win 10 专业版 22H2`
VScode: `1.81.1 x64`
Error: `command 'aide.codeViewerHelper' not found`

![AideError_01](https://github.com/nicepkg/aide/assets/112923496/0fb15bd1-3e53-4455-9632-d533b534732c)
![image](https://github.com/nicepkg/aide/assets/112923496/3a84326a-f0d4-4082-b860-89d27083e0a2)

**Comment by 2214962083** [comment]
可以在菜单—>帮助—>开发者工具，截一下关于aide的错误日志吗

**Comment by Shadow403** [comment]
> 可以在菜单—>帮助—>开发者工具，截一下关于aide的错误日志吗

我刚刚将 vscode 更新到最新版本
错误消失，没有拿到日志 (- -;)

**Comment by 2214962083** [comment]
好的感谢报告，暂时关闭此issue
