### ISSUE TITLE
暂停

### ISSUE THREAD

**Issue by anyiweb** [nicepkg/aide#20]
有办法可以暂停一下吗，一直输出没有办法关掉

**Comment by 2214962083** [comment]
下一版我会加上关掉输出文件就停止输出

**Comment by anyiweb** [comment]
> 下一版我会加上关掉输出文件就停止输出

谢谢作者！插件很有用，省去几步。

**Comment by Tendo33** [comment]
太需要停止输出功能了

**Comment by 2214962083** [comment]
`1.9.0` 版本已发布，加上两个功能，关闭文件即暂停输出，如果输出不齐全，点击 icon 会继续输出，你只需更新扩展即可。https://github.com/nicepkg/aide/pull/29
