### ISSUE TITLE
Azure 支持问题

### ISSUE THREAD

**Issue by mayunhe-cs** [nicepkg/aide#22]
请问可以提供Azure OpenAI的支持么，感谢！
参考 https://learn.microsoft.com/en-us/azure/ai-services/openai/quickstart?tabs=command-line%2Cpython-new&pivots=programming-language-javascript

**Comment by 2214962083** [comment]
可以考虑在下一版本推出

**Comment by 2214962083** [comment]
### 最新版 Aide `v1.12.0` 及以上已经适配了 Azure Openai，但是我没测试过，你可以尝试更新 aide 到最新版并执行以下配置：

**你的 azure baseUrl，请在最前面加上 `azure-openai@` 举例：**

**baseUrl:** `azure-openai@https://westeurope.api.microsoft.com/openai/deployments/gpt-4o-xxx/chat/completions?api-version=2024-07-15`

**key:** `你的 azure key`

**model:** `这个不用填`

**Comment by mayunhe-cs** [comment]
好的，感谢。

我试用后发现有些问题，当时提在这里了: https://github.com/nicepkg/aide/commit/607e5bd095ae97d8d7c3efc36c4efedfe71dacf4#r144230452

我的url是`openai.azure.com`域名下的，不清楚是否有`api.microsoft.com`域名的url

我在我的url前加上了`api.microsoft.com`，即改为了 `api.microsoft.comhttps://xxx.openai.azure.com/openai/deployments/gpt-4o?api-version=2024-03-01-preview`以通过这个if进入`AzureOpenAIModelProvider`，就可以正常使用了
