### ISSUE TITLE
关于对话的优化建议

### ISSUE THREAD

**Issue by btjawa** [nicepkg/aide#25]
当前的代码注释和代码转换已经做的很好了

在源代码比较长的情况下，回答中一次性可能给不完代码

希望可以在一次回答没有给全代码的情况下，携带上下文继续请求`continue`，然后追加回答到已有代码中

例如可以在一次回答完成后，检查回答开头的` ```language `，与末尾是否有对应的` ``` `完成闭包，如果没有，则继续请求

**Comment by 2214962083** [comment]
这个检测不是很严谨，首先呢，为了能够展示语言的高亮，我叫他不要给我任何Markdown语法，因此在open AI的模型里，很多时候是没有这个code block。无法判断是否中断。AI也不会总是遵循你的指令给你一种标准的响应格式。

其次，如果要继续生成的话，我觉得可以把交互设置为：人为手动再点一下那个icon，再把当前的翻译前和翻译后的上下文交给AI。叫AI继续完成上一次的代码。后者是可行的，我得实测一下。

感谢你的建议，这是一个优化用户体验的很好的建议

**Comment by btjawa** [comment]
好的，感谢

**Comment by 2214962083** [comment]
`1.9.0` 版本已发布，增加了点击icon继续生成功能，和自动去除markdown语法，你只需更新扩展即可。https://github.com/nicepkg/aide/pull/29
