### ISSUE TITLE
400 Range of top_p should be (0.0, 1.0)

### ISSUE THREAD

**Issue by mystery-byte** [nicepkg/aide#26]
这是我的阿里千问配置：
![image](https://github.com/nicepkg/aide/assets/174976674/3a223e8d-f7a0-4a35-b1d3-6959bbc1c615)

执行代码查看器助手报错400 Range of top_p should be (0.0, 1.0)
![image](https://github.com/nicepkg/aide/assets/174976674/e9e90789-0042-4971-9acc-92ed6840d318)

**Comment by 2214962083** [comment]
感谢报告，下一版修复

**Comment by 2214962083** [comment]
`1.9.0` 版本已发布，修复了此 bug，你只需更新扩展即可。https://github.com/nicepkg/aide/pull/29
