### ISSUE TITLE
400 invalid model ID

### ISSUE THREAD

**Issue by zzy133131** [nicepkg/aide#28]
千辛万苦搞了个官方的API，最后一个设置怎么填，模型怎么填呀，填gpt-3.5就说模型不存在，填gpt-3.5 turbo就报400 invalid model ID。文档说明里也没写清楚

**Comment by 2214962083** [comment]
openAI 的 key 要绑定国外卡才能用，建议填 `gpt-3.5-turbo`, 如果可以，填 `gpt-4o` 体验会更好，当然你也可以用国内的模型，他们都兼容了 openAI api 规范
