### ISSUE TITLE
假如我只能使用官方的免费gpt，可以使用该插件吗？

### ISSUE THREAD

**Issue by gwiguo** [nicepkg/aide#31]
如果可以的话，baseUrl和模型应该咋填呢，key我已经创建好了，劳烦大佬解答一下~

**Comment by 2214962083** [comment]
不可以，你必须要绑定国外的卡才能使用openai的key，如果你没有国外的卡那么你用国产模型也是可以的，比如通义千问、deepseek、智谱，配一下baseUrl和key和模型名字就行了
