### ISSUE TITLE
如何设置插件默认的 .vscode 目录路径

### ISSUE THREAD

**Issue by Bluuur** [nicepkg/aide#36]
在远程开发，使用代码语言转换时遇到以下错误：
`Failed to update configuration: Unable to write file 'vscode-remote://ssh-remote+xxxxxx/.vscode/settings.json' (NoPermissions (FileSystemError): Error: EACCES: permission denied, mkdir '/.vscode')`

在使用 VS Code 时，一般打开服务器的根目录进行开发，因为涉及多个项目文件的编写。但没有根目录的写入权限，如何将插件的 `.vscode` 路径指向 `~/.vscode` ？

**Comment by 2214962083** [comment]
语言转换功能会默认在当前项目记住你的偏好，并且由vscode存在.vscode/settings.json，这个存储位置是vscode决定的，当然后续我会出一个开关来关闭这个记忆功能

**Comment by 2214962083** [comment]
最新版增加了一个控制，允许关闭自动记忆功能：https://github.com/nicepkg/aide/blob/master/docs/configuration/README_CN.md#%E9%85%8D%E7%BD%AE---aideaideautorememberconvertlanguagepairs
