### ISSUE TITLE
配置了ts转js，但是不生效

### ISSUE THREAD

**Issue by SeaMmMm** [nicepkg/aide#39]
最开始转的时候在vscode里直接选的ts转cpp，后面在settings.json配置了ts转js，再转还是生成cpp，下面是我的配置
```json
  "aide.convertLanguagePairs": {
    "javascript": "typescript",
    "vue": "react",
    "react": "vue",
    "javascriptreact": "typescriptreact",
    "java": "typescript",
    "css": "scss",
    "scss": "css",
    "c": "typescript",
    "cpp": "typescript"
  }
```

**Comment by 2214962083** [comment]
你的配置里只有cpp转ts，不会存在ts转cpp, 你可以理解为左边的语言转成右边

**Comment by SeaMmMm** [comment]
> 你的配置里只有cpp转ts，不会存在ts转cpp, 你可以理解为左边的语言转成右边

现在我加了这条配置，他还是只会转成cpp
```json
  "aide.convertLanguagePairs": {
    "javascript": "typescript",
    "typescript": "javascript",
    "vue": "react",
    "react": "vue",
    "javascriptreact": "typescriptreact",
    "java": "typescript",
    "css": "scss",
    "scss": "css",
    "c": "typescript",
    "cpp": "typescript"
  }
```

**Comment by 2214962083** [comment]
我大概知道了，首先，vscode 有一份 global settings.json 文件存在你系统 user 文件夹下，同时还允许你在项目里配置 .vscode/settings.json ，然后他会合并两份文件，项目里的 .vscode/settings.json 权重会更大，你遇到的问题我猜测是你只改了全局的，但是项目里还有 .vscode/settings.json 的额外设置，你可以把项目 .vscode/settings.json 里相关的配置去掉

**Comment by SeaMmMm** [comment]
> 我大概知道了，首先，vscode 有一份 global settings.json 文件存在你系统 user 文件夹下，同时还允许你在项目里配置 .vscode/settings.json ，然后他会合并两份文件，项目里的 .vscode/settings.json 权重会更大，你遇到的问题我猜测是你只改了全局的，但是项目里还有 .vscode/settings.json 的额外设置，你可以把项目 .vscode/settings.json 里相关的配置去掉

已解决👍
