### ISSUE TITLE
请求自动删除Copyright、License注释

### ISSUE THREAD

**Issue by zijiren233** [nicepkg/aide#40]
很多项目文件的开头都有Copyright注释，希望复制AI Prompt的时候可以自动删除这些注释

**Comment by 2214962083** [comment]
感谢你的提议，但是经过一番考虑，他可能不在计划范围内，这是原因：

本扩展适用于任何语言，而每个语言的注释方式以及copyright的声明方式都是不同的，因此，无法做到实现一个通用的正则移除它。
