### ISSUE TITLE
[Feature request] 增加注释翻译功能

### ISSUE THREAD

**Issue by lc6464** [nicepkg/aide#42]
### 期望
- 添加大段注释转换功能
- 添加大段注释翻译功能
- 添加 DeepL/DeepLX API 配置功能

### 具体行为
- 可以将大段的注释复制为连贯的文本，而不是带有一大堆注释符号的 ~~抽象~~ 文本
- 可以将大段的注释通过大模型或 DeepL/DeepLX 翻译成多行注释形态的中文
- 可以将大段的注释通过大模型或 DeepL/DeepLX 翻译为连贯的中文，移除全部注释符号

### 情况说明
有时候别人的代码或库中会有**大段的英文注释**作为说明，如：
``` csharp
// Terminates this process and returns an exit code to the operating system.
// This is required to avoid the 'BackgroundServiceExceptionBehavior', which
// performs one of two scenarios:
// 1. When set to "Ignore": will do nothing at all, errors cause zombie services.
// 2. When set to "StopHost": will cleanly stop the host, and log errors.
//
// In order for the Windows Service Management system to leverage configured
// recovery options, we need to terminate the process with a non-zero exit code.
```

此时，常见的翻译工具鲜有能处理好这种情况的，我所了解的也只有 DeepL 效果还不错。
![image](https://github.com/user-attachments/assets/3aa41f33-69a6-4206-8cc7-b85e239f2f90)

所以，加上这三个功能还是相当有用的。<br/>
直接在 vscode 内即可翻译，不需要再去浏览器打开 DeepL 翻译页面。

~~另外，英专生也讨厌大段的英文。~~

**Comment by 2214962083** [comment]
你可以自定义代码查看助手的ai提示词，叫他遇到英文注释就翻译成中文。这是文档：https://github.com/nicepkg/aide/blob/master/docs/configuration/README_CN.md#%E9%85%8D%E7%BD%AE---aidecodeviewerhelperprompt

至于你要鼠标悬浮即翻译，用 ai 会很费 token，这个适合用传统翻译 api，这个扩展可能是你在找的：https://marketplace.visualstudio.com/items?itemName=intellsmi.comment-translate
