### ISSUE TITLE
翻译没有翻译完整，换了两个国产接口都是这样

### ISSUE THREAD

**Issue by vonch** [nicepkg/aide#45]
翻译没有翻译完整，换了两个国产接口都是这样

200多行的代码就不行。
![image](https://github.com/user-attachments/assets/2b58a8c9-6e06-434e-8b0b-0d0de943600d)

**Comment by vonch** [comment]
500多行代码。。。搞错了

**Comment by 2214962083** [comment]
即便模型支持128k上下文，它单次输出一般也就4k token左右，这是模型的限制，你可以再次点击原来的生成icon来继续

**Comment by angelanana** [comment]
> 即便模型支持128k上下文，它单次输出一般也就4k token左右，这是模型的限制，你可以再次点击原来的生成icon来继续

点击了原来的生成icon来继续之后，代码内输出了```go continue，然后右下角再次弹出继续吗的弹窗。 如图片所示。
![image](https://github.com/user-attachments/assets/8e2331f6-8905-455c-84ca-362b4841111e)

**Comment by 2214962083** [comment]
> > 即便模型支持128k上下文，它单次输出一般也就4k token左右，这是模型的限制，你可以再次点击原来的生成icon来继续
> 
> 点击了原来的生成icon来继续之后，代码内输出了```go continue，然后右下角再次弹出继续吗的弹窗。 如图片所示。 ![image](https://private-user-images.githubusercontent.com/63281354/351940766-8e2331f6-8905-455c-84ca-362b4841111e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NzY1MzUsIm5iZiI6MTcyMTg3NjIzNSwicGF0aCI6Ii82MzI4MTM1NC8zNTE5NDA3NjYtOGUyMzMxZjYtODkwNS00NTVjLTg0Y2EtMzYyYjQ4NDExMTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDAyNTcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmZDk4ZWE2NGFlMzA4OTY2Yzc4MzBhZjQ5MDc2Njk4N2NlODg5NDVmZTQ3MGQ2Yjc1MjMyNjEyM2M1ZTAxNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P5yzDwuOuy2Ie2PXXV8n7_j48s8sZOgJ0eMY0e9FVN0)

这个是因为模型能力问题，AI的输出我也无法控制，我只能尽可能优化提示词，关于继续生成这点，我建议你换open AI的转接商，效果会好点，你可以加我wechat: `qq2214962083` 交流

**Comment by angelanana** [comment]
希望暂停了之后，能够在暂停的位置，点击icon继续生成。目前要删掉这个文件重新开始。

**Comment by angelanana** [comment]
> > > 即便模型支持128k上下文，它单次输出一般也就4k token左右，这是模型的限制，你可以再次点击原来的生成icon来继续
> > 
> > 
> > 点击了原来的生成icon来继续之后，代码内输出了```go continue，然后右下角再次弹出继续吗的弹窗。 如图片所示。 ![image](https://private-user-images.githubusercontent.com/63281354/351940766-8e2331f6-8905-455c-84ca-362b4841111e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NzY1MzUsIm5iZiI6MTcyMTg3NjIzNSwicGF0aCI6Ii82MzI4MTM1NC8zNTE5NDA3NjYtOGUyMzMxZjYtODkwNS00NTVjLTg0Y2EtMzYyYjQ4NDExMTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDAyNTcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmZDk4ZWE2NGFlMzA4OTY2Yzc4MzBhZjQ5MDc2Njk4N2NlODg5NDVmZTQ3MGQ2Yjc1MjMyNjEyM2M1ZTAxNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P5yzDwuOuy2Ie2PXXV8n7_j48s8sZOgJ0eMY0e9FVN0)
> 
> 这个是因为模型能力问题，AI的输出我也无法控制，我只能尽可能优化提示词，关于继续生成这点，我建议你换open AI的转接商，效果会好点，你可以加我wechat: `qq2214962083` 交流
加了，等通过。

**Comment by angelanana** [comment]
> > > 即便模型支持128k上下文，它单次输出一般也就4k token左右，这是模型的限制，你可以再次点击原来的生成icon来继续
> > 
> > 
> > 点击了原来的生成icon来继续之后，代码内输出了```go continue，然后右下角再次弹出继续吗的弹窗。 如图片所示。 ![image](https://private-user-images.githubusercontent.com/63281354/351940766-8e2331f6-8905-455c-84ca-362b4841111e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NzY1MzUsIm5iZiI6MTcyMTg3NjIzNSwicGF0aCI6Ii82MzI4MTM1NC8zNTE5NDA3NjYtOGUyMzMxZjYtODkwNS00NTVjLTg0Y2EtMzYyYjQ4NDExMTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDAyNTcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmZDk4ZWE2NGFlMzA4OTY2Yzc4MzBhZjQ5MDc2Njk4N2NlODg5NDVmZTQ3MGQ2Yjc1MjMyNjEyM2M1ZTAxNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P5yzDwuOuy2Ie2PXXV8n7_j48s8sZOgJ0eMY0e9FVN0)
> 
> 这个是因为模型能力问题，AI的输出我也无法控制，我只能尽可能优化提示词，关于继续生成这点，我建议你换open AI的转接商，效果会好点，你可以加我wechat: `qq2214962083` 交流

加了，等通过

**Comment by 2214962083** [comment]
> 希望暂停了之后，能够在暂停的位置，点击icon继续生成。目前要删掉这个文件重新开始。

目前就支持这样子，但是ai输出不稳定，所以有时候它可能不听话，又从头再来，这是无法控制的
