### ISSUE TITLE
会考虑支持星火大模型吗

### ISSUE THREAD

**Issue by misakichan** [nicepkg/aide#49]

**Comment by 2214962083** [comment]
我看了一下星火官方文档，理论上现在就已经支持，后续考虑写进 `Aide` 文档里

**baseUrl:** `https://spark-api-open.xf-yun.com/v1`
**key:** `你的讯飞星火 key`
**model:** `generalv3.5`

星火参考文档：https://www.xfyun.cn/doc/spark/HTTP%E8%B0%83%E7%94%A8%E6%96%87%E6%A1%A3.html#_3-%E8%AF%B7%E6%B1%82%E8%AF%B4%E6%98%8E

**Comment by angelanana** [comment]
我尝试了一下，显示401 status code (no body)
![image](https://github.com/user-attachments/assets/6c7eed50-e3c7-4eb3-aab8-c734b29d7407)

**Comment by angelanana** [comment]
> 我尝试了一下，显示401 status code (no body) ![image](https://private-user-images.githubusercontent.com/63281354/351936670-6c7eed50-e3c7-4eb3-aab8-c734b29d7407.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NzUwNjcsIm5iZiI6MTcyMTg3NDc2NywicGF0aCI6Ii82MzI4MTM1NC8zNTE5MzY2NzAtNmM3ZWVkNTAtZTNjNy00ZWIzLWFhYjgtYzczNGIyOWQ3NDA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDAyMzI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyMDBmMjJhNTYwZDg5YmE1Y2VmM2M4OTdmYTc3MmM5YTAxYjIzODQwYWQxMjJjZjJkYTUzMjM1NmM4YTZmYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6G8o2vlHhAITgYzrUtHjRFaoPeD6EaTIQr17YsWsKJ0)

我知道了，不能这样写“key: 你的讯飞星火 key”，key需要是你的讯飞星火 key:你的讯飞星火 secret

**Comment by 2214962083** [comment]
文档已上线：https://aide.nicepkg.cn/zh/guide/use-another-llm/iflytek
