### ISSUE TITLE
gpt-4o，给文件添加注释，返回404

### ISSUE THREAD

**Issue by rexhang** [nicepkg/aide#52]
<img width="596" alt="image" src="https://github.com/user-attachments/assets/0da1d278-65db-48b0-8941-01f9d09d1034">

<img width="471" alt="image" src="https://github.com/user-attachments/assets/eeb39748-8904-4a16-a2d1-744fb9cbe33e">

<img width="691" alt="image" src="https://github.com/user-attachments/assets/3b109ae1-a1d1-45c3-80b0-b933e499d3d8">

版本: 1.91.1
提交: f1e16e1e6214d7c44d078b1f0607b2388f29d729
日期: 2024-07-09T22:07:46.768Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

网络正常，可是为何返回404呀。

**Comment by rexhang** [comment]
> <img alt="image" width="596" src="https://private-user-images.githubusercontent.com/14832793/350859085-0da1d278-65db-48b0-8941-01f9d09d1034.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MzAyOTcsIm5iZiI6MTcyMTYyOTk5NywicGF0aCI6Ii8xNDgzMjc5My8zNTA4NTkwODUtMGRhMWQyNzgtNjVkYi00OGIwLTg5NDEtMDFmOWQwOWQxMDM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA2MzMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4ZWIzN2ExNjdjNThjZjI5ODg3MzBiZDAxOGQ3OTM2M2E0OWU1ZTUxNWRjZTRlZWI2MTc3ZjgxZDFiZThiMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7txgqz1qHh20Td3XYXmrvxOFyp6AgR26fZW3FEJ8zx4"> <img alt="image" width="471" src="https://private-user-images.githubusercontent.com/14832793/350859199-eeb39748-8904-4a16-a2d1-744fb9cbe33e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MzAyOTcsIm5iZiI6MTcyMTYyOTk5NywicGF0aCI6Ii8xNDgzMjc5My8zNTA4NTkxOTktZWViMzk3NDgtODkwNC00YTE2LWEyZDEtNzQ0ZmI5Y2JlMzNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA2MzMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiODQ5MmNkN2VhNTY2Yzc5YjhhZWEyNTVmY2UwYTMyMDgyMGU0YTk5MzFhN2I2YWU5N2JlZWIzNTE2ODY3ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bp4-VO5r5zJ_BZ7clxyJ-RJQzYpUP5b-N3C89h1ujOE"> <img alt="image" width="691" src="https://private-user-images.githubusercontent.com/14832793/350859318-3b109ae1-a1d1-45c3-80b0-b933e499d3d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MzAyOTcsIm5iZiI6MTcyMTYyOTk5NywicGF0aCI6Ii8xNDgzMjc5My8zNTA4NTkzMTgtM2IxMDlhZTEtYTFkMS00NWMzLTgwYjAtYjkzM2U0OTlkM2Q4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA2MzMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlOTQ3NDhiYjk0YTc0ZTM4MGEyYjdkYjhkNGFiOTkzOWE1Mjg2NzJiODk4ZGM1YTJjMDE4OTllOTRmNDM1OWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JotHxB-HgX-OyO6iwS7Qq64RzgaiaQPWrkVh1HtW4Hw">
> 版本: 1.91.1 提交: f1e16e1e6214d7c44d078b1f0607b2388f29d729 日期: 2024-07-09T22:07:46.768Z Electron: 29.4.0 ElectronBuildId: 9728852 Chromium: 122.0.6261.156 Node.js: 20.9.0 V8: 12.2.281.27-electron.0 OS: Darwin arm64 23.5.0
> 
> 网络正常，可是为何返回404呀。

<img width="335" alt="image" src="https://github.com/user-attachments/assets/4f5ee00d-7021-4ea4-8409-63e1c3c9eba8">

**Comment by 2214962083** [comment]
api key 方式，即便是 gpt-3.5 也是要绑定国外卡付费的，你可以用国产模型或者购买api中转商的接口

**Comment by rexhang** [comment]
> api key 方式，即便是 gpt-3.5 也是要绑定国外卡付费的，你可以用国产模型或者购买api中转商的接口

那意思openai gpt-4o 在它们网页可以直接使用 但是用 apikey 不能自己通过接口三方调用嘛，https://api.openai.com/v1 接口收费？交钱才能调用模型接口。

**Comment by 2214962083** [comment]
> > api key 方式，即便是 gpt-3.5 也是要绑定国外卡付费的，你可以用国产模型或者购买api中转商的接口
> 
> 那意思openai gpt-4o 在它们网页可以直接使用 但是用 apikey 不能自己通过接口三方调用嘛，https://api.openai.com/v1 接口收费？交钱才能调用模型接口。

你的理解完全正确，这是openai的商业策略，我无法控制

**Comment by rexhang** [comment]
> > > api key 方式，即便是 gpt-3.5 也是要绑定国外卡付费的，你可以用国产模型或者购买api中转商的接口
> > 
> > 
> > 那意思openai gpt-4o 在它们网页可以直接使用 但是用 apikey 不能自己通过接口三方调用嘛，https://api.openai.com/v1 接口收费？交钱才能调用模型接口。
> 
> 你的理解完全正确，这是openai的商业策略，我无法控制

那好吧，请问下 我有什么办法能够 免费使用近似的模型能力呢，代码翻译加注释我感觉很有必要，希望能用上，国产的文心、千问，豆包，这些能申请到apikey，并且可以提供到baseURL调嘛？

**Comment by 2214962083** [comment]
> > > > api key 方式，即便是 gpt-3.5 也是要绑定国外卡付费的，你可以用国产模型或者购买api中转商的接口
> > > 
> > > 
> > > 那意思openai gpt-4o 在它们网页可以直接使用 但是用 apikey 不能自己通过接口三方调用嘛，https://api.openai.com/v1 接口收费？交钱才能调用模型接口。
> > 
> > 
> > 你的理解完全正确，这是openai的商业策略，我无法控制
> 
> 那好吧，请问下 我有什么办法能够 免费使用近似的模型能力呢，代码翻译加注释我感觉很有必要，希望能用上，国产的文心、千问，豆包，这些能申请到apikey，并且可以提供到baseURL调嘛？

我这里有很多模型配置教程， 我推荐你用 deepseek，主要是便宜，智商又足够用：https://aide.nicepkg.cn/zh/guide/use-another-llm/deepseek

**Comment by rexhang** [comment]
> > > > > api key 方式，即便是 gpt-3.5 也是要绑定国外卡付费的，你可以用国产模型或者购买api中转商的接口
> > > > 
> > > > 
> > > > 那意思openai gpt-4o 在它们网页可以直接使用 但是用 apikey 不能自己通过接口三方调用嘛，https://api.openai.com/v1 接口收费？交钱才能调用模型接口。
> > > 
> > > 
> > > 你的理解完全正确，这是openai的商业策略，我无法控制
> > 
> > 
> > 那好吧，请问下 我有什么办法能够 免费使用近似的模型能力呢，代码翻译加注释我感觉很有必要，希望能用上，国产的文心、千问，豆包，这些能申请到apikey，并且可以提供到baseURL调嘛？
> 
> 我这里有很多模型配置教程， 我推荐你用 deepseek，主要是便宜，智商又足够用：https://aide.nicepkg.cn/zh/guide/use-another-llm/deepseek

好的，Thanks.
