### ISSUE TITLE
请问有没有可能在code-server上使用该插件呢？

### ISSUE THREAD

**Issue by NJYZ-96** [nicepkg/aide#54]
[code-server](https://coder.com/docs/code-server)
这样可以在任何电脑的浏览器使用code

**Comment by 2214962083** [comment]
经过一番查阅，需要把Aide扩展发布到
https://open-vsx.org

才能在code-server上面使用，这有利于扩大使用人群，感谢你的建议，它已经提上议程了

**Comment by NJYZ-96** [comment]
> aider 现在已经推送到 `https://open-vsx.org/extension/nicepkg/aide-pro`， 你应该可以在 code-server 上面搜索使用了。
可以安装了；感谢大佬适配
瞄了一眼，配置项都是英文，有没有考虑做一下翻译呢？
我本来想用浏览器网页翻译，code-server 页面不支持网页翻译

**Comment by 2214962083** [comment]
> > aider 现在已经推送到 `https://open-vsx.org/extension/nicepkg/aide-pro`， 你应该可以在 code-server 上面搜索使用了。
> > 可以安装了；感谢大佬适配
> > 瞄了一眼，配置项都是英文，有没有考虑做一下翻译呢？
> > 我本来想用浏览器网页翻译，code-server 页面不支持网页翻译

扩展本身也支持中文，前提是你的编辑器是中文界面
这里也有中文文档：https://aide.nicepkg.cn/zh/guide/getting-started/
