### ISSUE TITLE
请求添加ai生成git commit message功能

### ISSUE THREAD

**Issue by zijiren233** [nicepkg/aide#56]

**Comment by zijiren233** [comment]
目前市面上的gptcommit以及个别一两个ai commit插件都因为长时间没有维护或不支持非openai gpt的模型而导致可用性大大降低

**Comment by 2214962083** [comment]
你提到的这个功能虽然很实用，但是它是在cli职责上面的，并不是VSCode扩展的职责。所以目前还没有明确的计划。感谢你的建议。
