### ISSUE TITLE
对jupyter文件使用自动注释，只会对第一个代码框生成对应文件

### ISSUE THREAD

**Issue by wrtppp** [nicepkg/aide#58]
如图
![图片1](https://github.com/user-attachments/assets/e0c4fe7e-34ff-494a-8027-86b56a9c11ab)

**Comment by 2214962083** [comment]
因为你选中了一行所以只有一行，如果你没有选中代码则是整个文件。

**Comment by wrtppp** [comment]
> 因为你选中了一行所以只有一行，如果你没有选中代码则是整个文件。

你好，谢谢你的回复，但是我不知道如何选中整个jupyter文件。即使退出对代码块的编辑、选中资源管理区的文件，再进行自动注释，自动注释依然只会对上一个选中的python代码块起作用

**Comment by 2214962083** [comment]
> > 因为你选中了一行所以只有一行，如果你没有选中代码则是整个文件。
> 
> 你好，谢谢你的回复，但是我不知道如何选中整个jupyter文件。即使退出对代码块的编辑、选中资源管理区的文件，再进行自动注释，自动注释依然只会对上一个选中的python代码块起作用

这个可能和vscode的机制有关，你试试ctrl+a全选，再点击icon试试

**Comment by wrtppp** [comment]
> > > 因为你选中了一行所以只有一行，如果你没有选中代码则是整个文件。
> > 
> > 
> > 你好，谢谢你的回复，但是我不知道如何选中整个jupyter文件。即使退出对代码块的编辑、选中资源管理区的文件，再进行自动注释，自动注释依然只会对上一个选中的python代码块起作用
> 
> 这个可能和vscode的机制有关，你试试ctrl+a全选，再点击icon试试

你好，他依然没有正常工作，还是只对局部生效

**Comment by 2214962083** [comment]
> > > > 因为你选中了一行所以只有一行，如果你没有选中代码则是整个文件。
> > > 
> > > 
> > > 你好，谢谢你的回复，但是我不知道如何选中整个jupyter文件。即使退出对代码块的编辑、选中资源管理区的文件，再进行自动注释，自动注释依然只会对上一个选中的python代码块起作用
> > 
> > 
> > 这个可能和vscode的机制有关，你试试ctrl+a全选，再点击icon试试
> 
> 你好，他依然没有正常工作，还是只对局部生效

感谢你的反馈，我看看是否有能力在下一版特意针对这个适配一下

**Comment by wrtppp** [comment]
感谢，期待您的更新
________________________________
发件人: ***@***.*** ***@***.***> 代表 JinmingYang ***@***.***>
发送时间: 2024年7月27日 06:15
收件人: nicepkg/aide ***@***.***>
抄送: wrtppp ***@***.***>; Author ***@***.***>
主题: Re: [nicepkg/aide] 对jupyter文件使用自动注释，只会对第一个代码框生成对应文件 (Issue #58)


因为你选中了一行所以只有一行，如果你没有选中代码则是整个文件。

你好，谢谢你的回复，但是我不知道如何选中整个jupyter文件。即使退出对代码块的编辑、选中资源管理区的文件，再进行自动注释，自动注释依然只会对上一个选中的python代码块起作用

这个可能和vscode的机制有关，你试试ctrl+a全选，再点击icon试试

你好，他依然没有正常工作，还是只对局部生效

感谢你的反馈，我看看是否有能力在下一版特意针对这个适配一下

―

**Comment by 2214962083** [comment]
> 感谢，期待您的更新

实测了一下，vscode 扩展无法从 ipynb 文件获取到 editor 对象，这更像是一个webview，测试转换源文件 json，ai 生成的 json 经常会破坏源格式，超出支持范围，从计划里划掉了。
