### ISSUE TITLE
讯飞模型调用后报错：(rawToolCalls ?? []) is not iterable

### ISSUE THREAD

**Issue by ghlgldd** [nicepkg/aide#67]
复制图片 在vscode中使用smart paste功能后报错 (rawToolCalls ?? []) is not iterable   
科大讯飞 4.0Ultra 模型

**Comment by 2214962083** [comment]
讯飞可能不支持tools调用(function_call)，因此可能用不了部分功能，如果想体验完整功能，还是建议用openai的gpt-4o

**Comment by ghlgldd** [comment]
> 讯飞可能不支持tools调用(function_call)，因此可能用不了部分功能，如果想体验完整功能，还是建议用openai的gpt-4o

感谢
