### ISSUE TITLE
请问考虑支持其他IDE吗？例如Jetbrains和Visual Studio

### ISSUE THREAD

**Issue by AlpineLX** [nicepkg/aide#69]
如题。以及如果使用本地模型，数据会被上传吗？

**Comment by 2214962083** [comment]
使用本地模型数据不会被上传，你甚至可以断网用，不过有些功能要模型支持function_call或者读图，本地模型可能不支持，因此可能用不了完整功能。

对于jetbrains，社区呼声很高，但要等能人异士适配了，我暂时没能力实现。

vs可能永远不会被支持，人力有限。

**Comment by AlpineLX** [comment]
谢谢！辛苦了！
