### ISSUE TITLE
转换的语言类型配置完没有用

### ISSUE THREAD

**Issue by zsk-coder** [nicepkg/aide#76]
最开始装完选了一次语言，后面不管是配置文件里面指定转换的语言，还是卸载重装插件，都没有用，打开还是第一次选择的语言

**Comment by 2214962083** [comment]
修改你项目里的 .vscode/settings.json文件里的aide.convertLanguagePairs

你可以阅读一下这篇文档末尾 https://aide.nicepkg.cn/zh/guide/features/code-convert
