### ISSUE TITLE
vscode插件昨天还用的挺好, 今天完全不响应

### ISSUE THREAD

**Issue by liuwa666** [nicepkg/aide#77]
出现的具体问题就是: 使用aide的任何功能, vscode右下角的弹窗都提示正在处理, 但过去很长时间都没有响应
是否是因为今天更新了vscode 1.92.0的原因?
![image](https://github.com/user-attachments/assets/0c483f43-b33d-475d-b980-68f5bd7fc40f)
![image](https://github.com/user-attachments/assets/daedd0f9-a661-4948-92cf-8da0b55a9d9a)
![image](https://github.com/user-attachments/assets/bea1249c-5d94-44fd-ae37-d87b2f5bf6e0)

**Comment by liuwa666** [comment]
换成deepseek的api后, 右键点击问AI后, 调用aider在命令行窗口回答问题都是好的, 都没有问题. 但aide自身的其他功能都用不了, vscode右下角弹窗都是这个状态:
![image](https://github.com/user-attachments/assets/6363bb14-3668-4c86-a006-143e4818d2ee)

**Comment by 2214962083** [comment]
如果你是在用批量处理文件，那么响应久是正常的。

如果不是，那我猜测是你的网络问题，你可以尝试开启一下代理，又或者关闭Aide默认使用系统代理选项：https://aide.nicepkg.cn/zh/guide/configuration/use-system-proxy

你可以点击右上角的icon测试加注释功能，以确认API是否可用

**Comment by zy9703** [comment]
> 如果你是在用批量处理文件，那么响应久是正常的。
> 
> 如果不是，那我猜测是你的网络问题，你可以尝试开启一下代理，又或者关闭 Aide 默认使用系统代理选项：https://aide.nicepkg.cn/zh/guide/configuration/use-system-proxy
> 
> 你可以点击右上角的 icon 测试加注释功能，以确认 API 是否可用

我这边更新vscode最新1.92.0后点击代码注释功能后也出现一直处理中问题，而回退老版本后会立马响应没有一直处理中的问题。我的openai在别的平台测试没有问题，可以排除是网络代理的问题。应该是vscode版本更新导致的问题。

**Comment by 2214962083** [comment]
> > 如果你是在用批量处理文件，那么响应久是正常的。
> > 如果不是，那我猜测是你的网络问题，你可以尝试开启一下代理，又或者关闭 Aide 默认使用系统代理选项：https://aide.nicepkg.cn/zh/guide/configuration/use-system-proxy
> > 你可以点击右上角的 icon 测试加注释功能，以确认 API 是否可用
> 
> 我这边更新vscode最新1.92.0后点击代码注释功能后也出现一直处理中问题，而回退老版本后会立马响应没有一直处理中的问题。我的openai在别的平台测试没有问题，可以排除是网络代理的问题。应该是vscode版本更新导致的问题。

@zy9703 @liuwa666 
感谢反馈，测试下来感觉是 `VSCode` 自身原因，不过我已经通过其他办法暂时性修复了，`Aide` 更新到 `v1.17.2` 即可正常运行
