### ISSUE TITLE
提示：潜在的密钥泄露安全问题

### ISSUE THREAD

**Issue by Jamesinit** [nicepkg/aide#78]
不应该将key保存在Setting.json中。

因为Vscode为了使设置实时生效，是允许插件读取setting.json的。

如果存在恶意插件，或者使用Github仓库管理Setting.json 的同步就会有泄露风险。
获取Setting.json 实例代码：
```
 let all = await vscode.workspace.getConfiguration();

  let allAsJSON = JSON.parse(JSON.stringify(all));  // the key line

  const editorSettings = allAsJSON.editor;
```

应该使用Vscode 的SecretStorage。
https://code.visualstudio.com/api/references/vscode-api#SecretStorage

**Comment by 2214962083** [comment]
尽管你提到的安全问题确实存在。但是目前我不打算修复它。

1. 用户不需要在settings.json里面设置key，它可以在设置界面设置，这并不会创建一个项目级别settings.json。
2. 虽然其他扩展也可以读取这个key，但是相应的很多第三方web UI要求用户设置环境变量OPENAI_KEY，那样子安全性一样有问题。
3. 为什么不用secret storage，因为这样子增删改key都要自己实现设置界面，一来对于维护难度增加，二来很多用户都是偏小白，普通设置他都搞不懂，这会增加用户的使用成本。

也许在未来，aide通过webview重写了设置界面会考虑进去这一点，但在目前而言，并没有改变的计划，同时很感谢你的提议
