### ISSUE TITLE
How to set `Doubao` model

### ISSUE THREAD

**Issue by kurorinto** [nicepkg/aide#80]
My settings is as follows:
```json
{
    "aide.openaiBaseUrl": "https://ark.cn-beijing.volces.com/api/v3",
    "aide.openaiModel": "Doubao-pro-128k/240628",
    "aide.openaiKey": "my-doubao-apikey"
}
```
But is don't work, the `error message` is
```
404 The request targeted an endpoint that does not exist or is invalid. Request id: 
02172282444093840571e3ce5f26177b37c29bf9d076c3b40a73e
``` 
![image](https://github.com/user-attachments/assets/a615d1aa-8faf-4f62-b383-53c029711ca5)

**Comment by 2214962083** [comment]
Your model name is incorrect，follow doubao document, it should be start with `ep-xxx` https://www.volcengine.com/docs/82379/1263482

**Comment by kurorinto** [comment]
Thanks🙏
