### ISSUE TITLE
vscode最新版1.92.0下用ai批处理文件功能没有生成文件副本

### ISSUE THREAD

**Issue by liuwa666** [nicepkg/aide#81]
如题, aide已升级到1.17.2, 在vscode左侧资源管理器右键选中文件后, 选择ai批量处理文件, 然后输入命令, 右下角弹窗已显示批处理任务完成, 但并没有生成相应的文件副本, 换其他不同的模型api也不行, 应该是一个bug, 请修复, 谢谢. 我用的是windows10系统

**Comment by 2214962083** [comment]
你用的是什么语言模型

**Comment by 2214962083** [comment]
测试了一下，发现是windows独有的bug，已经在 Aide 最新版 `v1.17.3` 修复，感谢报告此 bug
