### ISSUE TITLE
读C++的.h文件时，aide的注释文件生成的是cpp

### ISSUE THREAD

**Issue by tonychen99** [nicepkg/aide#83]
读C++的.h文件时，aide的注释文件生成的是cpp，使用替换原文按钮会把原本的.h文件替换成.cpp，这个有解决方法吗

**Comment by 2214962083** [comment]
这应该是个bug，我看看是否有办法解决它，感谢你的报告

**Comment by 2214962083** [comment]
该 bug 已经修复，更新到最新的 `v1.18.0` 版即可。

**Comment by tonychen99** [comment]
bug确实已经被修复了，目前使用一切正常，感谢您的付出
