### ISSUE TITLE
单.CPP文件，使用qwen-long模型，智能重命名变量功能有问题

### ISSUE THREAD

**Issue by tonychen99** [nicepkg/aide#84]
错误信息：No tools_call in message [{"message":{"lc":1,"type":"constructor","id":["langchain_core","messages","AIMessage"],"kwargs":{"content":"Sure!根据代码片段中提供的上下文，变量“m_quantity”似乎代表了书籍的数量。为了使变量名更有意义并遵守代码中使用的命名惯例，这里有一些建议：\n\n1. `m_bookQuantity`: 这个名字清楚地表明它代表书籍的数量。\n\n2. `m_quantityOfBooks`: 这个名字遵循与 `m_name`和 `m_price`相同的模式，使其与现有的命名约定一致。\n\n3. `m_numBooks`: `m_numBooks`: 比之前的建议短，这个名字也工作得很好，通常用于表示数量。\n\n4. `m_stockQuantity`: 如果变量旨在表示库存数量，这可能是一个不错的选择。\n\n5. `m_inventoryCount`: 这个名字表明变量计数库存。\n\n鉴于这些选项，我建议使用`m_bookQuantity`或`m_quantityOfBooks`，因为它们最符合现有的命名惯例，并清楚地描述了变量的目的。","tool_calls":[],"invalid_tool_calls":[],"additional_kwargs":{},"response_metadata":{"tokenUsage":{"completionTokens":213,"promptTokens":198,"totalTokens":411},"finish_reason":"stop"},"id":"chatcmpl-c60932ed-40be-9532-824b-4d795c7ea8ea"}},"text":"Sure!根据代码片段中提供的上下文，变量“m_quantity”似乎代表了书籍的数量。为了使变量名更有意义并遵守代码中使用的命名惯例，这里有一些建议：\n\n1. `m_bookQuantity`: 这个名字清楚地表明它代表书籍的数量。\n\n2. `m_quantityOfBooks`: 这个名字遵循与 `m_name`和 `m_price`相同的模式，使其与现有的命名约定一致。\n\n3. `m_numBooks`: `m_numBooks`: 比之前的建议短，这个名字也工作得很好，通常用于表示数量。\n\n4. `m_stockQuantity`: 如果变量旨在表示库存数量，这可能是一个不错的选择。\n\n5. `m_inventoryCount`: 这个名字表明变量计数库存。\n\n鉴于这些选项，我建议使用“m_bookQuantity”或“m_quantityOfBooks”，因为它们与现有的命名约定最接近，并清楚地描述了变量的目的。"}]
使用qwen-max模型报错 400 field required: payload.parameters.tools.0.function.description

**Comment by 2214962083** [comment]
该功能需要模型支持function_call，千问不支持所以用不了

**Comment by tonychen99** [comment]
好的，我了解了，因为之前看千问官方的文档有提到function_call的调用，我以为可以的。好像他们的function_call我看报错是提交参数错误。现在换成deepseek已经可以了，感谢您！
