### ISSUE TITLE
未找到 aide.readClipboardImage

### ISSUE THREAD

**Issue by Astronaut-X-X** [nicepkg/aide#85]
![image](https://github.com/user-attachments/assets/6e3cd95e-1121-4ea4-9675-1fb646a81c1c)

**Comment by Astronaut-X-X** [comment]
![image](https://github.com/user-attachments/assets/14efa88d-3ad4-495b-8ed3-3d2db078019d)

**Comment by Astronaut-X-X** [comment]
![image](https://github.com/user-attachments/assets/73826089-0af4-4371-94c7-1574f6b69958)

**Comment by 2214962083** [comment]
更新Aide到最新版，重启vscode
