### ISSUE TITLE
aide官网充值后没有给我Key

### ISSUE THREAD

**Issue by anlun214** [nicepkg/aide#89]
如题，我该如何是好。

**Comment by anlun214** [comment]
<img width="334" alt="image" src="https://github.com/user-attachments/assets/195b02a8-bae6-4037-8246-d147a7182097">

**Comment by 2214962083** [comment]
充值完之后是会有页面显示 密钥 给你复制的，如果你还填了邮箱，也是会有邮件发到你邮箱，如果都没有，你可以加QQ联系售后

**Comment by anlun214** [comment]
联系到作者后反应非常迅速，及时解决了我的问题，马上使用了起来，真的太棒了！
