### ISSUE TITLE
有关jetbrain IDE的版本的问题

### ISSUE THREAD

**Issue by zazedwhwhy** [nicepkg/aide#90]
大佬nb，询问一下请问有计划为插件做jetbrain IDE的版本吗

**Comment by 2214962083** [comment]
目前没有相关计划喔，如果你有能力将它适配到jetbrains，我非常欢迎pr：https://github.com/nicepkg/aide/issues/16

**Comment by zazedwhwhy** [comment]
ok

**Comment by zazedwhwhy** [comment]
但是不会写TypeScript (￫ܫ￩)
