### ISSUE TITLE
智能代码转换,不能自定义

### ISSUE THREAD

**Issue by JACKCHEN99** [nicepkg/aide#92]
## 版本
aide版本: v1.18.0
vscode版本:  1.92.1 (Universal)

## 问题
第一次测试"智能代码转换", 选择把shell脚本, 转换为windows的bat脚本, 之后无论是:
1. 自定义"aide.convertLanguagePairs"
2. 设置"aide.autoRememberConvertLanguagePairs": false,
3. 卸载aide插件, 并且删除~/.vscode-server/extensions/nicepkg.aide-pro-1.18.0, 然后重装

最后再code covert,一个 shell脚本, 还是没有选择弹窗, 默认转换为了bat脚本
不知道为什么...有相同情况的不
<img width="1591" alt="image" src="https://github.com/user-attachments/assets/fb7d2357-6e26-4c35-8a7b-c8a90f1feb55">

**Comment by 2214962083** [comment]
`settings.json` 文件不仅仅在用户级别目录有，在项目级别里面也有，`aide.convertLanguagePairs` 默认是记录在项目级别的，删除你项目文件夹里的`.vscode/settings.json` 文件就好了，

**Comment by JACKCHEN99** [comment]
我试试, 

> `settings.json` 文件不仅仅在用户级别目录有，在项目级别里面也有，`aide.convertLanguagePairs` 默认是记录在项目级别的，删除你项目文件夹里的`.vscode/settings.json` 文件就好了，

谢谢, 找到了, 我还以为见了鬼👻了. 刚用vscode, 对它的配置不是很了解, chatgpt问了也没说这块...
大部分插件, 配置应该都是放用于级别的配置里的. 这样的话, 有点不太友好, 排查了半天. 插件的文档里也没看到, 估计其他人也会遇到这个问题

**Comment by 2214962083** [comment]
> 我试试,
> 
> > `settings.json` 文件不仅仅在用户级别目录有，在项目级别里面也有，`aide.convertLanguagePairs` 默认是记录在项目级别的，删除你项目文件夹里的`.vscode/settings.json` 文件就好了，
> 
> 谢谢, 找到了, 我还以为见了鬼👻了. 刚用vscode, 对它的配置不是很了解, chatgpt问了也没说这块... 大部分插件, 配置应该都是放用于级别的配置里的. 这样的话, 有点不太友好, 排查了半天. 插件的文档里也没看到, 估计其他人也会遇到这个问题

将会写进文档
