### ISSUE TITLE
代码行距太大，能否修复一下

### ISSUE THREAD

**Issue by devyujie** [nicepkg/aide#93]
系统：win10
编辑器：Cursor

![image](https://github.com/user-attachments/assets/f9c1f1fd-9af0-493d-8352-e96966278fb1)

**Comment by 2214962083** [comment]
windows bug，下一版修复

**Comment by 2214962083** [comment]
改功能已经在 Aide 最新版 `v1.19.0` 修复，更新到最新版即可，如果没有自动更新，可以重启 vscode 再手动更新。

**Comment by devyujie** [comment]
感谢，已经好了
