### ISSUE TITLE
Aide 模型聚合配置好后使用报错

### ISSUE THREAD

**Issue by xvweirong** [nicepkg/aide#95]
Aide 模型聚合可用，在其它插件已确认，怀疑是Aide本身问题，具体报错如下：

1. 点击 Aide Usage, 报错：Failed to fetch usage info: Error fetching usage info: HTTP error! status: 403
2. 点击 Code Viewer Helper等功能报错：Azure OpenAI API instance name not found

**Comment by 2214962083** [comment]
请截图你的配置，打码key

**Comment by 2214962083** [comment]
你是不是按照azure-openai来配了，请严格遵循Aide聚合模型配置文档来配：https://aide.nicepkg.cn/zh/guide/use-another-llm/aide-models#%E7%A4%BA%E4%BE%8B%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6

**Comment by xvweirong** [comment]
![AIDE config](https://github.com/user-attachments/assets/ed228544-304d-47a7-be25-d77872eda52f)
配置如图，User和Workspace都一样的设置。

**Comment by 2214962083** [comment]
> ![AIDE config](https://private-user-images.githubusercontent.com/1329308/362151705-ed228544-304d-47a7-be25-d77872eda52f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MjUxMDQsIm5iZiI6MTcyNDgyNDgwNCwicGF0aCI6Ii8xMzI5MzA4LzM2MjE1MTcwNS1lZDIyODU0NC0zMDRkLTQ3YTctYmUyNS1kNzc4NzJlZGE1MmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjhUMDYwMDA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDY5ZjBjNDdhMzQ2MjY5OGI3NDg5OWM4OTk1MGUxMDg0NjFkNTNmMTg5MDFmNGNjYzgwM2E2MjAyMGM3NmJmMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AtJpkMirYmuPTCd-lxMZ8rX827MQ5QxxKPRQ3hg0Qmw) 配置如图，User和Workspace都一样的设置。

配置并没有错，看看你项目文件夹下.vscode/settings.json文件是否存在额外配置

**Comment by xvweirong** [comment]
检查过了，项目文件夹下.vscode/settings.json配置是相同的。也试过清空这个项目文件夹下的配置文件，重启vs code，还是一样的情况，不知道问题出在哪里。

**Comment by xvweirong** [comment]
有usage的URL 吗，我试试在cmd里curl调用，看看是否会报错。

**Comment by 2214962083** [comment]
> 有usage的URL 吗，我试试在cmd里curl调用，看看是否会报错。
```sh
curl https://api.zyai.online/v1/models \
  -H "Authorization: Bearer 你的aide key"
```

**Comment by xvweirong** [comment]
可能是被公司默认的 Zscaler 挡住了，Use System Proxy 是否要设置为false？ Aide是否支持手动设置proxy？谢谢。

**Comment by 2214962083** [comment]
> 可能是被公司默认的 Zscaler 挡住了，Use System Proxy 是否要设置为false？ Aide是否支持手动设置proxy？谢谢。

我不认为这是代理问题，代理问题并不会报这个错，这是最终读取url读出了azure-openai@https://xxxxx，导致instance name没有从url提取出来而出了问题。

**Comment by xvweirong** [comment]
检查了 AppData\Roaming\Code\User\settings.json 和  .vscode/settings.json 的配置，确保没错，还有其他地方可能会保存base url配置的吗？

**Comment by 2214962083** [comment]
> 试过挺多编程插件，看到User\settings.json里面有一些chatgpt相关配置，都删除了，没有azure相关的。其他插件：Codegeex, marscode, Continue，Tongyi Lingma 插件应该都不冲突吧？关闭后重新打开还是一样的情况。我回去找台干净的电脑再试试。

奇怪，方便的话我可以晚上8点远程帮你debug

**Comment by xvweirong** [comment]
找到原因了，有个 .env 文件，里面定义了一些环境变量，包括：AZURE_OPENAI_API_BASE_URL 和 AZURE_OPENAI_API_KEY，注释掉重启VS Code后可以正常使用Aide功能了，没想到这个也会影响插件。

但点击 Aide Usage按钮还是报错： Failed to fetch usage info: Error fetching usage info: HTTP error! status: 403 有什么线索吗？

**Comment by 2214962083** [comment]
> 找到原因了，有个 .env 文件，里面定义了一些环境变量，包括：AZURE_OPENAI_API_BASE_URL 和 AZURE_OPENAI_API_KEY，注释掉重启VS Code后可以正常使用Aide功能了，没想到这个也会影响插件。
> 
> 但点击 Aide Usage按钮还是报错： Failed to fetch usage info: Error fetching usage info: HTTP error! status: 403 有什么线索吗？

可能我用的langchain包，它调用了openai官方包，官方包会把这个优先级置于我传进去的参数之前，这个没办法

**Comment by 2214962083** [comment]
> 现在Usage按钮不起作用，我不知道有多少余额，这个有什么办法查询吗？

usage余额查询只支持Aide聚合模型api，因为这个接口没有统一的规范，openai也没开放查询余额接口，其他各家各写各的，所以没适配
