### ISSUE TITLE
有没有分析代码生成流程图的计划

### ISSUE THREAD

**Issue by PeterGuy326** [nicepkg/aide#96]
我现在在公司实现了一套服务间的架构调用流程图，类似于 zipkin 实现的流程图
现在想要做每个接口内部的逻辑代码分析，自动生成流程图，并生成对应流程图输出管理好文档，有无该计划，我想集成

**Comment by 2214962083** [comment]
没有相关计划，但是Aide有一个功能可能能帮到你，把你一键复制所有代码，让你可以粘贴到别的Web端叫AI帮你生成这个流程图：

https://aide.nicepkg.cn/zh/guide/features/copy-as-prompt
