### ISSUE TITLE
按照官方文档配置了ollama的url，key和model但一直显示Aide正在处理中

### ISSUE THREAD

**Issue by liu247** [nicepkg/aide#99]
![Snipaste_2024-09-06_09-11-13](https://github.com/user-attachments/assets/87f41377-e372-4f04-9fe0-5145302d8211)

**Comment by 2214962083** [comment]
https://aide.nicepkg.cn/zh/guide/configuration/use-system-proxy

关闭这个设置，重启vscode看看

**Comment by 1AoB** [comment]
404 The model `gpt-4o` does not exist or you do not have access to it.

**Comment by 2214962083** [comment]
> 404 The model `gpt-4o` does not exist or you do not have access to it.

OpenAI 的 API 调用方式所有模型都是收费的，它和 Chatgpt web 版 是区别开来的，所以你必须绑定信用卡。

**Comment by 1AoB** [comment]
ok

**Comment by liu247** [comment]
> https://aide.nicepkg.cn/zh/guide/configuration/use-system-proxy
> 
> 关闭这个设置，重启vscode看看

有效果，多谢
